# Generated by Django 3.0.7 on 2020-11-14 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evolution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('pokemon', models.IntegerField(primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=0, verbose_name='Order of evolution if have one')),
                ('is_baby', models.BooleanField(verbose_name='Is a baby?')),
                ('name', models.CharField(max_length=100, verbose_name='Pokemon name')),
                ('hp', models.IntegerField(verbose_name='Hit points')),
                ('attack', models.IntegerField(verbose_name='Attack points')),
                ('deffense', models.IntegerField(verbose_name='Deffense points')),
                ('special_attack', models.IntegerField(verbose_name='Special Attack points')),
                ('special_deffense', models.IntegerField(verbose_name='Special Deffense points')),
                ('speed', models.IntegerField(verbose_name='Speed points')),
                ('evolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.Evolution')),
            ],
        ),
    ]
