# Generated by Django 3.0.7 on 2020-11-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_auto_20201114_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='special_deffense',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='special_defense',
            field=models.IntegerField(default=0, verbose_name='Special Deffense points'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='attack',
            field=models.IntegerField(default=0, verbose_name='Attack points'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='defense',
            field=models.IntegerField(default=0, verbose_name='Deffense points'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='hp',
            field=models.IntegerField(default=0, verbose_name='Hit points'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='is_baby',
            field=models.BooleanField(default=False, verbose_name='Is a baby?'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='special_attack',
            field=models.IntegerField(default=0, verbose_name='Special Attack points'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='speed',
            field=models.IntegerField(default=0, verbose_name='Speed points'),
        ),
    ]
