# Generated by Django 3.0.7 on 2020-11-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0005_auto_20201115_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='weight',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='evolution_graph',
            field=models.CharField(blank=True, max_length=100, verbose_name='Evolution graph'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='height',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10, verbose_name='Height points'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='width',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10, verbose_name='Width points'),
        ),
    ]
