# Generated by Django 3.0.7 on 2020-11-15 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0006_auto_20201115_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='height',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Height points'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='width',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Width points'),
        ),
    ]
