# Generated by Django 3.0.7 on 2020-11-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0008_auto_20201115_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='evolution_graph',
            field=models.TextField(blank=True, max_length=100, verbose_name='Evolution graph'),
        ),
    ]
