# Generated by Django 3.0.7 on 2020-11-15 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0010_auto_20201115_0422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='pokemon',
            new_name='pokemon_pk',
        ),
    ]
