# Generated by Django 3.0.7 on 2020-11-15 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0011_auto_20201115_0424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evolution',
            old_name='pokemon_id',
            new_name='pokemon',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='pokemon_pk',
            new_name='pokemon',
        ),
    ]
