# Generated by Django 3.0.7 on 2020-11-15 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0012_auto_20201115_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evolution',
            name='pokemon',
        ),
    ]
