# Generated by Django 3.0.7 on 2020-11-15 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0013_remove_evolution_pokemon'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolution',
            name='pokemon',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pokemon.Pokemon'),
        ),
    ]
