# Generated by Django 3.0.7 on 2020-11-15 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0014_evolution_pokemon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evolution_details',
        ),
    ]
