# Generated by Django 3.0.7 on 2020-11-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0015_delete_evolution_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolution',
            name='chain_evol',
            field=models.TextField(default=''),
        ),
    ]
